import { Typography } from "@mui/material";
import { Container } from "@mui/system";
import Head from "next/head";
import { useContext } from "react";
import Loader from "../components/loader/Loader";
import { BusinessContext } from "../services/businessContext";

export default function Home() {
  const { loading } = useContext(BusinessContext);
  if (loading) {
    return <Loader />;
  }
  return (
    <div>
      <Head>
        <title>let's talk</title>/{/* <title>You talkie</title> */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        style={{
          marginTop: 100,
        }}
      >
        <Typography
          style={{
            fontFamily: "Pacifico",
          }}
          variant="h2"
        >
          You Talkie
        </Typography>
      </Container>
    </div>
  );
}
